@startuml
'Hecho
Hecho --> Contribuyente
Hecho --> Origen
Hecho --> Categoria
Hecho --> Ubicacion
Hecho -->"*" Etiqueta
Hecho --o Coleccion

Solicitud --* Hecho

Coleccion --> Criterio
Coleccion ..> Criterio

'Criterio
Criterio --> RangoFechas
Criterio --> Origen
Criterio --> Categoria
Criterio --> Ubicacion

Solicitud --> EstadoSolicitud

'Interface
ElementoCriterio <|-- Ubicacion
ElementoCriterio <|-- Categoria
ElementoCriterio <|-- Etiqueta
ElementoCriterio <|-- RangoFechas

class Contribuyente {
    -nombre: String
    -apellido:
    -edad: Integer
}

enum EstadoSolicitud {
    ACEPTADA,
    RECHAZADA,
    PENDIENTE
}

class Hecho {
    -titulo: String
    -descripcion: String
    -categoria: Categoria
    -ubicacion: Ubicacion
    -etiquetas: <List>Etiqueta
    -fechaAcontecimiento: Date
    -fechaCarga: Date
    -origen: Origen
    -contribuyente: Contribuyente
    -eliminado: Boolean
    -imagenes: <List>String
    -audios: <List>String
    -videos: <List>String
    +eliminar(): Integer
    +tieneContenidoMultimedia(): Boolean
}

class Etiqueta {

}

enum Origen {
    MANUAL
    DATASET
    CONTRIBUYENTE
}

class Categoria {
    -titulo: String
}

class Ubicacion {
    -latitud: String
    -longitud: String
}

class Solicitud {
    -hecho: Hecho
    -fundamento: String
    -rechazada: Boolean
    +serAceptada(): Integer
    +serRechazada(): Integer
}

class Coleccion {
    -hechos: <Set> Hecho
    -titulo: String
    -descripcion: String
    -criterio: Criterio
    +agregarHecho(hecho: Hecho): Integer
    +eliminarHecho(hecho: Hecho): Integer
    'Solo para representar overload
    +consultarHechos(): <Set> Hecho
    +consultarHechos(filtros: <Set> Filtros): <Set> Hecho
}

class Criterio{
    -requisitoTitulo: String
    -requisitoDescripcion: String
    -categoria: Categoria
    -tieneContenidoMultimedia: Boolean
    -ubicacion: Ubicacion
    -fechaAcontecimientoEntre: RangoFechas
    -fechaDeCargaEntre: RangoFechas
    -origen: Origen
    +cumpleCriterio(hecho: Hecho): Boolean
    -tituloContiene(titulo: String): Boolean
    -descripcionContiene(descripcion: String): Boolean
    -cumpleOrigen(origen: Origen): Boolean
}

class RangoFechas {
    -fechaInicio: Date
    -fechaFin: Date
    +coincide(date: Date): Boolean
}

interface ElementoCriterio{
    +coincide(algo): Boolean
}
@enduml