@startuml
'Hecho
Hecho --> Contribuyente
Hecho --> Origen
Hecho --> Categoria
Hecho --> Ubicacion
Hecho -->"*" Etiqueta
Hecho --o Coleccion

Solicitud --* Hecho

Coleccion --> Criterio

'Criterio
Criterio --> RangoFechas
Criterio --> Origen
Criterio --> Categoria
Criterio --> Ubicacion

Solicitud --> EstadoSolicitud

'Interface
ElementoCriterio <|-- Ubicacion
ElementoCriterio <|-- Categoria
ElementoCriterio <|-- Etiqueta
ElementoCriterio <|-- RangoFechas

ContenidoMultimedia --> Formato
Hecho --> ContenidoMultimedia
Coleccion <.. ImportadorHechos

class Contribuyente {
    -nombre: String
    -apellido:
    -edad: Integer
}

enum EstadoSolicitud {
    ACEPTADA,
    RECHAZADA,
    PENDIENTE
}

class ContenidoMultimedia {
    -nombre: String
    -ruta: String
    -formato: Formato
}

enum Formato {
    VIDEO
    AUDIO
    IMAGEN
}

class Hecho {
    -titulo: String
    -descripcion: String
    -categoria: Categoria
    -ubicacion: Ubicacion
    -etiquetas: <List>Etiqueta
    -fechaAcontecimiento: LocalDate
    -fechaCarga: LocalDate
    -origen: Origen
    -contribuyente: Contribuyente
    -eliminado: Boolean
    -contenidoMultimedia: List<ContenidoMultimedia>
    +eliminar(): Integer
    +tieneContenidoMultimedia(): Boolean
    +estaEliminado(): Boolean
}

class ImportadorHechos {
    -rutaArchivo: String
    +cargarColeccion(Coleccion coleccion): Integer
}

class Etiqueta {
    -titulo: String
}

enum Origen {
    MANUAL
    DATASET
    CONTRIBUYENTE
}

class Categoria {
    -titulo: String
}

class Ubicacion {
    -latitud: String
    -longitud: String
}

class Solicitud {
    -hecho: Hecho
    -fundamento: String
    -rechazada: Boolean
    -fechaResolucion: LocalDate
    +serAceptada(): Integer
    +serRechazada(): Integer
}

class Coleccion {
    -hechos: <List> Hecho
    -titulo: String
    -descripcion: String
    -criterios: <List> Criterio
    -fuentes: <List> Fuente
    +agregarHecho(hecho: Hecho): Integer
    +eliminarHecho(hecho: Hecho): Integer
    'Solo para representar overload
    +consultarHechos(): <List> Hecho
    +consultarHechos(filtros: <List> Filtros): <List> Hecho
    +recalcularHechos(): Integer

}

class Criterio{
    -requisitoTitulo: String
    -requisitoDescripcion: String
    -categoria: Categoria
    -tieneContenidoMultimedia: Boolean
    -ubicacion: Ubicacion
    -fechaAcontecimientoEntre: RangoFechas
    -fechaDeCargaEntre: RangoFechas
    -origen: Origen
    +cumpleCriterio(hecho: Hecho): Boolean
    -cumpleTitulo(titulo: String): Boolean
    -cumpleDescripcion(descripcion: String): Boolean
    -cumpleOrigen(origen: Origen): Boolean
}

class RangoFechas {
    -fechaInicio: LocalDate
    -fechaFin: LocalDate
    +coincide(date: LocalDate): Boolean
}

interface ElementoCriterio{
    +coincide(algo): Boolean
}
@enduml