@startuml
'Hecho
 Hecho --> Contribuyente
 Hecho --> EstadoHecho

'HechoRevisadoInputDTO
 HechoRevisadoInputDTO --> EstadoHecho

'HechoOutputDTO
 HechoOutputDTO --> Contribuyente

'IContribuyenteRepository
 IContribuyenteRepository ..> Contribuyente

'ContribuyenteRepository
 ContribuyenteRepository ..|> IContribuyenteRepository
 ContribuyenteRepository -->"*" Contribuyente

'IDinamicaRepository
 IDinamicaRepository ..> Hecho

'DinamicaRepository
 DinamicaRepository ..|> IDinamicaRepository
 DinamicaRepository -->"*" Hecho

'IDinamicaService
 IDinamicaService ..> HechoOutputDTO
 IDinamicaService ..> HechoInputDTO
 IDinamicaService ..> HechoModificadoInputDTO
 IDinamicaService ..> HechoRevisadoInputDTO
 IDinamicaService ..> Contribuyente

'DinamicaService
 DinamicaService ..|> IDinamicaService
 DinamicaService --> IDinamicaRepository
 DinamicaService --> IContribuyenteRepository

'DinamicaController
 DinamicaController --> IDinamicaService

class HechoInputDTO {

    - String nombreUsuario
    - Integer edadUsuario
    - String titulo
    - String descripcion
    - String categoria
    - String urlMultimedia
    - String ubicacion
    - LocalDate fechaAcontecimiento
}

class HechoModificadoInputDTO {

    - Long id
    - String nombreUsuario
    - Integer edadUsuario
    - String titulo
    - String descripcion
    - String categoria
    - String urlMultimedia
    - String ubicacion
    - LocalDate fechaAcontecimiento
}

class HechoRevisadoInputDTO {

    - Long idAdministrador
    - Long idHecho
    - List<String> etiquetas
    - EstadoHecho estadoHecho
    - String sugerenciaDeCambio
}

class HechoOutputDTO {
    - Contribuyente contribuyente
    - String titulo
    - String descripcion
    - String categoria
    - String urlMultimedia
    - String ubicacion
    - LocalDate fechaAcontecimiento
    - List<String> etiquetas
}

class Hecho {

    - Long id
    - Contribuyente contribuyente
    - String  titulo
    - String descripcion
    - String categoria
    - String urlMultimedia
    - String ubicacion
    - LocalDate fechaAcontecimiento
    - List<String> etiquetas
    - LocalDate fechaGuardado
    - EstadoHecho estadoHecho
    - String sugerenciaDeCambio
    - List<String> etiquetas
}

class Contribuyente {
    - Long id
    - String nombre
    - Integer edad
}

enum EstadoHecho {
    PENDIENTE,
    ACEPTADA,
    ACEPTADA_CON_SUGERENCIA,
    RECHAZADA
}

interface IContribuyenteRepository {

    + guardar(Contribuyente contribuyente):void
    + comprobarUsuarioRegistrado(Contribuyente contribuyente):Boolean

}

class ContribuyenteRepository{

    - List<Contribuyente> contribuyentes

    + guardar(Contribuyente contribuyente):void
    + comprobarUsuarioRegistrado(Contribuyente contribuyente):Boolean
}

interface IDinamicaRepository {

    + buscarPorID (Long ID):Hecho
    + guardar(Hecho hecho):void
    + guardarCambios(Hecho hechoOriginal, Hecho hechoCambiado):void
    + eliminar(Hecho hecho):void
    + mostrarTodos():List<Hecho>
    + mostrarEnviados(Boolean enviado):List<Hecho>

}

class DinamicaRepository{

    - List<Hecho> hechos

    + buscarPorID (Long ID):Hecho
    + guardar(Hecho hecho):void
    + guardarCambios(Hecho hechoOriginal, Hecho hechoCambiado):void
    + eliminar(Hecho hecho):void
    + mostrarTodos():List<Hecho>
    + mostrarEnviados(Boolean enviado):List<Hecho>
    - estadoAceptado(Hecho hecho):Boolean
}

interface IDinamicaService {

    + buscarHechos():List<HechoOutputDTO>
    + crear(HechoInputDTO hechoInputDTO):HechoOutputDTO
    + eliminar(Long id):void
    + actualizar(HechoModificadoInputDTO hechoModificado):HechoOutputDTO
    + verificarUsuarioRegistrado(Contribuyente contribuyente):Boolean
    + gestionarHecho(HechoRevisadoInputDTO hechoRevisado):HechoOutputDTO

}

class DinamicaService{

    - IDinamicaRepository dinamicaRepository
    - IContribuyenteRepository contribuyentesRepository

    + buscarHechos():List<HechoOutputDTO>
    + crear(HechoInputDTO hechoInputDTO):HechoOutputDTO
    + actualizar(HechoModificadoInputDTO hecho)HechoOutputDTO
    + eliminar(Long id):void
    + verificarUsuarioRegistrado(Contribuyente contribuyente):Boolean
    + gestionarHecho(HechoRevisadoInputDTO hechoRevisado):HechoOutputDTO
    - hechoOutputDTO(Hecho hecho):HechoOutputDTO
    - buscarPorID(Long id):Hecho
    - verificarTiempoParaActualizar(Hecho hecho)
}

class DinamicaController{

    - IDinamicaService dinamicaService

    + buscarTodos(Boolean enviado):List<HechoOutputDTO>
    + solicitudCrearHecho(HechoInputDTO hecho):HechoOutputDTO
    + actualizarHecho(HechoModificadoInputDTO hecho):HechoOutputDTO
    + gestionarHecho(HechoRevisadoInputDTO hechoRevisado):HechoOutputDTO
    - verificarEdadNecesaria(HechoInputDTO hecho):Boolean
    - verificarUsuarioRegistrado(HechoModificadoInputDTO hecho):Boolean

}
@enduml