spring.application.name=fuente-dinamica
server.port=${PORT}

# Configuraci?n de la base de datos
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Servicios
servicio.dinamica=${URL_PROPIA}

# Configuraaci?n de sincronizaci?n de entities contra la base de datos
spring.jpa.hibernate.ddl-auto=update
# none: no toca la BD.
# validate: valida que las entidades coincidan con la BD.
# update: actualiza la BD seg?n las entidades (muy usado en desarrollo).
# create: crea las tablas en cada inicio.
# create-drop: igual que create pero borra al apagar.

spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# Configuracion de Eureka Client
eureka.client.service-url.defaultZone=${SERVICEREGISTRY_URL}
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.hostname=${EUREKA_INSTANCE_HOSTNAME:localhost}
eureka.instance.non-secure-port=${EUREKA_INSTANCE_NON_SECURE_PORT:8081}
eureka.instance.prefer-ip-address=false
eureka.instance.instance-id=${eureka.instance.hostname}:${spring.application.name}:${eureka.instance.non-secure-port}

# Mantener la conexi?n viva
eureka.instance.lease-renewal-interval-in-seconds=30
eureka.instance.lease-expiration-duration-in-seconds=90

# Configuracion de Actuator para health checks
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always