@startuml

entity estadistica_hechos <<fact_table>> {
    id INTEGER(11) <<PK>>
    coleccion_id VARCHAR(100)  <<FK>>
    provincia VARCHAR(100)
    categoria_id VARCHAR(100) <<FK>>
    hora TIME
    --
    cantidad_hechos BIGINT
}

entity coleccion <<dimension>> {
    id INTEGER(11) <<FK>>
    --
    coleccion_detalle VARCHAR(100)
}

entity categoria <<dimension>> {
    id INTEGER(11) <<FK>>
    --
    categoria_detalle VARCHAR(100)
}

entity solicitud<<fact_table>> {
    id INTEGER(11)  <<FK>>
    --
    solicitud_spam BOOLEAN <<FK>>
}

estadistica_hechos }o--|| coleccion
estadistica_hechos }o--|| categoria


@enduml