@startuml

entity estadistica_hechos {
    id INTEGER(11) <<PK>>
    coleccion_id VARCHAR(100)  <<FK>>
    provincia VARCHAR(100)
    categoria_id VARCHAR(100) <<FK>>
    hora TIME
    --
    hechos INTEGER(11) <<FK>>
}

entity hechos_x_estadistica {
    estadistica_id INTEGER(11) <<PK,FK>>
    hecho_id INTEGER(11) <<PK,FK>>
    --
}

entity coleccion {
    id INTEGER(11) <<FK>>
    --
    coleccion_detalle VARCHAR(100)
}

entity categoria {
    id INTEGER(11) <<FK>>
    --
    categoria_detalle VARCHAR(100)
}

entity solicitud_eliminacion {
    id INTEGER(11)  <<PK>>
    --
    estado VARCHAR(50) <<FK>>
}

entity hecho {
    id INTEGER(11) <<PK>>
    --
}

estadistica_hechos }o--|| coleccion
estadistica_hechos }o--|| categoria
estadistica_hechos }o--|| hechos_x_estadistica
hecho }o--|| hechos_x_estadistica
solicitud_eliminacion |o--|| hecho

@enduml