    @startuml
    'Hecho
    Hecho --> Contribuyente
    Hecho --> Origen
    Hecho --> Categoria
    Hecho --> Ubicacion
    Hecho -->"*" Etiqueta
    Hecho --o Coleccion
    Hecho -->"*" ContenidoMultimedia
    Hecho --> Fuente

    'Solicitudes de Eliminacion
    SolicitudEliminacion --* Hecho
    SolicitudEliminacion --> EstadoSolicitudEliminacion
    SolicitudEliminacion --> ResolucionSolicitudEliminacion
    SolicitudEliminacion --> Contribuyente

    'Resoluciones de Solicitudes de Eliminacion
    ResolucionSolicitudEliminacion --> Administrador

    'Colecciones
    Coleccion --> Criterio
    Coleccion ..> Filtro
    Coleccion --> AlgConsenso
    AlgConsenso --> IStratConsenso
    AlgConsensoMultMenciones ..|> IStratConsenso
    AlgConsensoMaySimple ..|> IStratConsenso
    AlgConsensoAbsoluto ..|> IStratConsenso
    AlgConsenso --> Fuente


    'Fuente
    Coleccion --> Fuente
    Fuente ..> Hecho
    Fuente --> TipoFuente

    AdapImpHDinamico ..|> IAdapImpH
    AdapImpHEstatico ..|> IAdapImpH
    AdapImpHProxy ..|> IAdapImpH
    AdapImpC ..|> IAdapImpC

    Fuente --> IAdapImpC
    Fuente --> IAdapImpH

    'Criterio
    Criterio --> Filtro

    'ElementoCriterio
    Filtro <|.. FiltroTitulo
    Filtro <|.. FiltroCategoria
    Filtro <|.. FiltroFechaAcontecimiento

    'Estrategias
    FiltroCategoria --> Categoria
    FiltroFechaAcontecimiento --> RangoFechas

    'Contenido Multimedia
    ContenidoMultimedia --> Formato


    class Contribuyente {
        -nombre: String
        -apellido: String
        -fechaNacimiento: LocalDate
        +laEdadEs(): Integer
    }

    class Administrador {
        -nombre: String
        -apellido: String
    }

    enum EstadoSolicitudEliminacion {
        ACEPTADA,
        RECHAZADA,
        PENDIENTE
    }

    class ResolucionSolicitudEliminacion {
        -fechaResolucion: LocalDateTime
        -administrador: Administrador
    }

    class ContenidoMultimedia {
        -nombre: String
        -ruta: String
        -formato: Formato
    }

    enum Formato {
        VIDEO
        AUDIO
        IMAGEN
    }

    class Hecho {
        -id: Long
        -idHFuente: Long
        -titulo: String
        -descripcion: String
        -categoria: Categoria
        -ubicacion: Ubicacion
        -etiquetas: <List>Etiqueta
        -fechaAcontecimiento: LocalDate
        -fechaCarga: LocalDate
        -origen: Origen
        -contribuyente: Contribuyente
        -eliminado: Boolean
        -fuente: Fuente
        -idFuente: Long
        -contenidoMultimedia: List<ContenidoMultimedia>
        +eliminar(): Void
        +estaEliminado(): Boolean
        +tieneContenidoMultimedia(): Boolean
    }

    class Fuente {
        -nombre: String
        -path: String
        -webClient: WebClient
        -tipoFuente: TipoFuente
        -adapImpH: IAdapImpH
        -adapImpC: IAdapImpC
        +importarHechos(): List<Hecho> hechos
        +buscarNuevosHechos(LocalDateTime ultimaFechaRefresco): List<Hecho>
        +eliminarHecho(Hecho hecho): void
    }

    enum TipoFuente {
        ESTATICA,
        DIMAMICA,
        PROXY
    }

    interface IAdapImpH {
        +importarHechos(): List<Hecho> hechos
        +buscarNuevosHechos(LocalDateTime ultimaFechaRefresco): List<Hecho>
        +eliminarHecho(Hecho hecho): void
    }


    class AdapImpHDinamico {
        +importarHechos(): List<Hecho> hechos
        +buscarNuevosHechos(LocalDateTime ultimaFechaRefresco): List<Hecho>
        +eliminarHecho(Hecho hecho): void
    }

    class AdapImpHEstatico {
        +importarHechos(): List<Hecho> hechos
        +buscarNuevosHechos(LocalDateTime ultimaFechaRefresco): List<Hecho>
        +eliminarHecho(Hecho hecho): void
    }

    class AdapImpHProxy {
        +importarHechos(): List<Hecho> hechos
        +buscarNuevosHechos(LocalDateTime ultimaFechaRefresco): List<Hecho>
        +eliminarHecho(Hecho hecho): void
    }

    interface IAdapImpC {
        +importarColecciones(): List<Coleccion> colecciones
        +importarColeccion(): Coleccion coleccion
    }

    class AdapImpC {
        +importarColecciones(): List<Coleccion> colecciones
        +importarHechosColeccion(Long id): List<Hecho> hechos
    }

    class Etiqueta {
        -titulo: String
    }

    enum Origen {
        MANUAL
        DATASET
        CONTRIBUYENTE
    }

    class Categoria {
        -titulo: String
    }

    class Ubicacion {
        -latitud: String
        -longitud: String
    }

    class SolicitudEliminacion {
        -hecho: Hecho
        -fundamento: String
        -estadoSolicitudEliminacion: EstadoSolicitudEliminacion
        -fechaCreacion: LocalDateTime
        -resolucionSolicitud: ResolucionSolicitudEliminacion
        -contribuyente: Contribuyente
        +serAceptada(): Void
        +serRechazada(): Void
    }

    class Coleccion {
        -fuente: <List> Fuente
        -hechos: <List> Hecho
        -hechosConsensuados: <List> Hecho
        -titulo: String
        -descripcion: String
        -criterio: Criterio
        -algConsenso: AlgConsenso
        +cargarHechos(hechos: <List> Hecho): <List> Hecho
        +consultarHechos(): <List> Hecho
        +consultarHechos(filtros: <List> Filtro): <List> Hecho
        +consultarHechosCurados(): <List> Hecho
        +consultarHechosCurados(filtros: <List> Filtro): <List> Hecho
        +agregarFiltroACriterio(filtro: Filtro): Boolean
        +recalcularHechos(): <List> Hecho
    }

    class Criterio{
        -filtros: <List> Filtro

        +cumpleCriterio(hecho: Hecho): Boolean
        +agregarFiltro((Filtro filtro): Void
    }

    class AlgConsenso {
        -fuentes: <List> Fuente
        -stratConsenso: <List> IStratConsenso
        +consensuados(hechos: <List> Hecho): <List> Hecho
    }

    class AlgConsensoMaySimple {
        +consensuados(hechos: <List> Hecho, fuentes: <List> Fuente): <List> Hecho
    }

    class AlgConsensoMultMenciones {
        +consensuados(hechos: <List> Hecho, fuentes: <List> Fuente): <List> Hecho
    }

    class AlgConsensoAbsoluto {
        +consensuados(hechos: <List> Hecho, fuentes: <List> Fuente): <List> Hecho
    }

    interface IStratConsenso {
        +consensuados(hechos: <List> Hecho, fuentes: <List> Fuente): <List> Hecho
    }

    interface Filtro{
        +coincide(algo): Boolean
    }

    class RangoFechas {
        -fechaInicio: LocalDate
        -fechaFin: LocalDate
    }

    class FiltroTitulo{
        -titulo: String
        +coincide(algo): Boolean
    }

    class FiltroFechaAcontecimiento{
        -fechaAcontecimientoEntre: RangoFechas
        +coincide(algo): Boolean
    }

    class FiltroCategoria{
        -categoria: Categoria
        +coincide(algo): Boolean
    }

    @enduml