@startuml
'Hecho
Hecho --> Contribuyente
Hecho --> Origen
Hecho --> Categoria
Hecho --> Ubicacion
Hecho -->"*" Etiqueta
Hecho --o Coleccion
Hecho -->"*" ContenidoMultimedia
Hecho --> Fuente
Hecho --> Consenso

'Solicitudes de Eliminacion
SolicitudEliminacion --* Hecho
SolicitudEliminacion --> EstadoSolicitudEliminacion
SolicitudEliminacion --> ResolucionSolicitudEliminacion
SolicitudEliminacion --> Contribuyente

'Resoluciones de Solicitudes de Eliminacion
ResolucionSolicitudEliminacion --> Administrador

'Colecciones
Coleccion --> Criterio
Coleccion ..> Filtro
Coleccion --> Consenso

Consensuador --> IStratConsenso
Consensuador ..> Consenso
Consensuador ..> Hecho
AlgConsensoMultMenciones ..|> IStratConsenso
AlgConsensoMaySimple ..|> IStratConsenso
AlgConsensoAbsoluto ..|> IStratConsenso


'Fuente
Coleccion --> Fuente
Fuente ..> Hecho
Fuente --> TipoFuente

AdapImpHDinamico ..|> IAdapImpH
AdapImpHEstatico ..|> IAdapImpH
AdapImpHProxy ..|> IAdapImpH
AdapImpC ..|> IAdapImpC

Fuente --> IAdapImpC
Fuente --> IAdapImpH

'Criterio
Criterio --> Filtro

'ElementoCriterio
Filtro <|.. FiltroCategoria
Filtro <|.. FiltroEtiqueta
Filtro <|.. FiltroFechaAcontecimientoFinal
Filtro <|.. FiltroFechaAcontecimientoInicio
Filtro <|.. FiltroFechaCargaFinal
Filtro <|.. FiltroFechaCargaInicio
Filtro <|.. FiltroLatitud
Filtro <|.. FiltroLongitud
Filtro <|.. FiltroTitulo

'Estrategias
FiltroCategoria --> Categoria

'Contenido Multimedia
ContenidoMultimedia --> Formato


class Contribuyente {
    -nombre: String
    -apellido: String
    -fechaNacimiento: LocalDate
    +laEdadEs(): Integer
}

class Administrador {
    -nombre: String
    -apellido: String
}

enum EstadoSolicitudEliminacion {
    ACEPTADA,
    RECHAZADA,
    PENDIENTE
}

class ResolucionSolicitudEliminacion {
    -fechaResolucion: LocalDateTime
    -administrador: Administrador
}

class ContenidoMultimedia {
    -nombre: String
    -ruta: String
    -formato: Formato
}

enum Formato {
    VIDEO
    AUDIO
    IMAGEN
}

class Hecho {
    -id: Long
    -idInternoFuente: Long
    -titulo: String
    -descripcion: String
    -categoria: Categoria
    -ubicacion: Ubicacion
    -etiquetas: <List>Etiqueta
    -fechaAcontecimiento: LocalDate
    -fechaCarga: LocalDate
    -origen: Origen
    -contribuyente: Contribuyente
    -consensos: <List> Consenso
    -estaEliminado: Boolean
    -fuente: Fuente
    -idFuente: Long
    -contenidoMultimedia: List<ContenidoMultimedia>
    +eliminar(): Void
    +estaEliminado(): Boolean
    +tieneContenidoMultimedia(): Boolean
}

class Fuente {
    -nombre: String
    -path: String
    -webClient: WebClient
    -tipoFuente: TipoFuente
    -adapImpH: IAdapImpH
    -adapImpC: IAdapImpC
    +importarHechos(): List<Hecho> hechos
    +buscarNuevosHechos(LocalDateTime ultimaFechaRefresco): List<Hecho>
    +eliminarHecho(Hecho hecho): void
    +importarColecciones(): List<Coleccion> colecciones
    +importarColeccion(Long id): Coleccion coleccion
    +importarHechosColeccion(Long id): List<Hecho> hechos
}

enum TipoFuente {
    ESTATICA,
    DIMAMICA,
    PROXY
}

interface IAdapImpH {
    +importarHechos(WebCliente webClient,): List<Hecho> hechos
    +buscarNuevosHechos(WebCliente webClient,LocalDateTime ultimaFechaRefresco): List<Hecho>
    +eliminarHecho(WebCliente webClient,Hecho hecho): void
}


class AdapImpHDinamico {
    +importarHechos(WebCliente webClient): List<Hecho> hechos
    +buscarNuevosHechos(WebCliente webClient, LocalDateTime ultimaFechaRefresco): List<Hecho>
    +eliminarHecho(WebCliente webClient, Hecho hecho): void
}

class AdapImpHEstatico {
    +importarHechos(WebCliente webClient): List<Hecho> hechos
    +buscarNuevosHechos(WebCliente webClient, LocalDateTime ultimaFechaRefresco): List<Hecho>
    +eliminarHecho(WebCliente webClient, Hecho hecho): void
}

class AdapImpHProxy {
    +importarHechos(WebCliente webClient): List<Hecho> hechos
    +buscarNuevosHechos(WebCliente webClient, LocalDateTime ultimaFechaRefresco): List<Hecho>
    +eliminarHecho(WebCliente webClient, Hecho hecho): void
}

interface IAdapImpC {
    +importarColecciones(WebClient webClient): List<Coleccion> colecciones
    +importarColeccion(WebClient webClient, Long id): Coleccion coleccion
    +importarHechosColeccion(WebClient webClient, Long id): List<Hecho> hechos
}

class AdapImpC {
    +importarColecciones(WebClient webClient, ): List<Coleccion> colecciones
    +importarColeccion(WebClient webClient, Long id): Coleccion coleccion
    +importarHechosColeccion(WebClient webClient, Long id): List<Hecho> hechos
}

class Etiqueta {
    -titulo: String
}

enum Origen {
    MANUAL
    DATASET
    CONTRIBUYENTE
}

class Categoria {
    -titulo: String
}

class Ubicacion {
    -latitud: String
    -longitud: String
}

class SolicitudEliminacion {
    -hecho: Hecho
    -fundamento: String
    -estadoSolicitudEliminacion: EstadoSolicitudEliminacion
    -fechaCreacion: LocalDateTime
    -resolucionSolicitud: ResolucionSolicitudEliminacion
    -contribuyente: Contribuyente
    +serAceptada(): Void
    +serRechazada(): Void
}

class Coleccion {
    -fuente: <List> Fuente
    -hechos: <List> Hecho
    -titulo: String
    -descripcion: String
    -criterio: Criterio
    -consenso: <List> Consenso
    +cargarHechos(hechos: <List> Hecho): <List> Hecho
    +consultarHechos(): <List> Hecho
    +consultarHechos(filtros: <List> Filtro): <List> Hecho
    +consultarHechosCurados(): <List> Hecho
    +consultarHechosCurados(filtros: <List> Filtro): <List> Hecho
    +agregarFiltroACriterio(filtro: Filtro): Boolean
    +recalcularHechos(): <List> Hecho
    +refrescar(): void
    +refrescar(ultimoRefresco: DateTime): void
}

class Criterio{
    -filtros: <List> Filtro

    +cumpleCriterio(hecho: Hecho): Boolean
    +agregarFiltro((Filtro filtro): Void
}

class Consensuador {
    -stratConsensos: <List> IStratConsenso
    +consensuarHechos(fuentes: <List> Fuentes, hecho: <List> Hecho): <List> Hecho
    -pedirHechosRepetidos(fuentes: <List> Fuentes, hecho: <List> Hecho): <List> Hecho
}

class AlgConsensoMaySimple {
    +consensuados(hechos: <List> Hecho, fuentes: <List> Fuente): <List> Hecho
}

class AlgConsensoMultMenciones {
    +consensuados(hechos: <List> Hecho, fuentes: <List> Fuente): <List> Hecho
}

class AlgConsensoAbsoluto {
    +consensuados(hechos: <List> Hecho, fuentes: <List> Fuente): <List> Hecho
}

interface IStratConsenso {
    +consensuados(hechos: <List> Hecho, fuentes: <List> Fuente): <List> Hecho
}

enum Consenso {
    ABSOLUTO,
    MULTMENCIONES,
    MAYSIMPLE
}



interface Filtro{
    +coincide(algo): Boolean
}

class FiltroCategoria{
    -categoria: Categoria
    +coincide(algo): Boolean
}

class FiltroEtiqueta {
    -nombre: String
    +coincide(algo): Boolean
}

class FiltroFechaAcontecimientoInicio {
    -fechaInicio: LocalDate
    +coincide(algo): Boolean
}

class FiltroFechaAcontecimientoFinal {
    -fechaFinal: LocalDate
    +coincide(algo): Boolean
}

class FiltroFechaCargaInicio {
    -fechaInicio: LocalDate
    +coincide(algo): Boolean
}

class FiltroFechaCargaFinal {
    -fechaFinal: LocalDate
    +coincide(algo): Boolean
}

class FiltroLatitud{
    -latitud: String
    +coincide(algo): Boolean
}

class FiltroLongitud{
    -longitud: String
    +coincide(algo): Boolean
}

class FiltroTitulo{
    -titulo: String
    +coincide(algo): Boolean
}

@enduml