spring.application.name=agregador

# Configuracion de la base de datos
spring.datasource.url=jdbc:mysql://localhost:3306/metamapa_agregador?useSSL=false&serverTimezone=America/Argentina/Buenos_Aires&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=123456789
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuracion de sincronizacion de entities contra la base de datos
spring.jpa.hibernate.ddl-auto=update
# none: no toca la BD.
# validate: valida que las entidades coincidan con la BD.
# update: actualiza la BD según las entidades (muy usado en desarrollo).
# create: crea las tablas en cada inicio.
# create-drop: igual que create pero borra al apagar.

spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# Configuraciones
server.port=8082

#Sentry
sentry.dsn=https://0e8a81e1c5254393d5736c2c293c2707@o4510399990792192.ingest.us.sentry.io/4510399993675776
sentry.environment=development
sentry.traces-sample-rate=1.0
sentry.send-default-pii=true
sentry.logs.enabled=true
#lo de aca abajo es para debuggear (podes ver que funciona el sentry con esto debbugs)
#sentry.debug=true

# Deshabilitar OTLP local para evitar el error
otel.exporter.otlp.endpoint=
otel.sdk.disabled=false

# Configuración de Eureka Client
eureka.client.service-url.defaultZone=http://localhost:8088/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true
eureka.instance.lease-renewal-interval-in-seconds=30
eureka.instance.lease-expiration-duration-in-seconds=90

# Configuracion de Actuator para health checks
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

# Timeouts para manejar fuentes grandes
spring.mvc.async.request-timeout=600000
server.tomcat.connection-timeout=600000
feign.client.config.default.connectTimeout=600000
feign.client.config.default.readTimeout=600000
