spring.application.name=agregador

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

eureka.client.service-url.defaultZone=${SERVICEREGISTRY_URL}
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

eureka.instance.prefer-ip-address=false
eureka.instance.hostname=${PUBLIC_HOSTNAME}
eureka.instance.non-secure-port=80
eureka.instance.secure-port-enabled=false

eureka.instance.home-page-url=${URL_PROPIA}
eureka.instance.health-check-url=${URL_PROPIA}actuator/health
eureka.instance.status-page-url=${URL_PROPIA}actuator/info

eureka.instance.instance-id=${PUBLIC_HOSTNAME}:${spring.application.name}:80

eureka.instance.lease-renewal-interval-in-seconds=15
eureka.instance.lease-expiration-duration-in-seconds=45

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
management.server.port=8082

spring.cloud.loadbalancer.cache.enabled=true
spring.cloud.loadbalancer.cache.capacity=256
spring.cloud.loadbalancer.cache.ttl=35s