spring.application.name=client
ruta.archivos=./client/public/media-uploads/
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

server.servlet.encoding.charset=UTF-8
spring.mvc.charset=UTF-8
server.servlet.encoding.force=true

# Servicios
servicio.agregador=${URL_AGREGADOR}
servicio.dinamica=${URL_DINAMICA}
servicio.auth=${URL_AUTH}
servicio.estadisticas=${URL_ESTADISTICAS}
servicio.apiGateway=${URL_GATEWAY}
servicio.estatica=${URL_ESTATICA}


# El interruptor maestro: apaga completamente el cliente de Eureka
eureka.client.enabled=false

# (Opcional) Refuerzo para asegurar que no intente registrarse ni buscar servicios
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false