spring.application.name=client
hechos.service.url=http://localhost:8084/hechos
hechos.service.url=http://localhost:8081/coleccion
dinamica.service.url=http://localhost:8081/api/fuenteDinamica
server.port=8085