spring.application.name=client
ruta.archivos=./client/public/media-uploads/
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

server.servlet.encoding.charset=UTF-8
spring.mvc.charset=UTF-8
server.servlet.encoding.force=true

# Servicios
servicio.agregador=http://localhost:8082
servicio.proxy=http://localhost:8083
servicio.estatica=http://localhost:8084
servicio.dinamica=http://localhost:8081/api/fuenteDinamica
servicio.auth=http://localhost:8087/auth
servicio.estadisticas=http://localhost:8085/estadisticas