spring.application.name=servicio-autenticacion
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
server.port=${PORT}

SECRET_KEY=mySecretKey123456789012345678901234567890

# Configuracion de Eureka Client
eureka.client.service-url.defaultZone=${SERVICEREGISTRY_URL}
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true
eureka.instance.lease-renewal-interval-in-seconds=30
eureka.instance.lease-expiration-duration-in-seconds=90

eureka.instance.hostname=${EUREKA_INSTANCE_HOSTNAME:localhost}
eureka.instance.non-secure-port=${EUREKA_INSTANCE_NON_SECURE_PORT:8087}
eureka.instance.instance-id=${eureka.instance.hostname}:${spring.application.name}:${eureka.instance.non-secure-port}


# Configuracion de Actuator para health checks
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always